#spring:
#  application:
#    name: authorization
#  security:
#    oauth2:
#      client:
#        registration:
#          # "google" is the {registrationId}
#          google:
#            client-id: "YOUR-CLIENT-ID"
#            client-secret: "YOUR-CLIENT-SECRET"
#            scope:
#              - openid
#              - profile
#              - email
#          # "google" is the {registrationId}
#          # Provider settings are not required, but can be added explicitly
#          # spring-boot-starter-oauth2-client automatically knows Google's issuer-uri
#        # provider:
#        #   google:
#        #     issuer-uri: https://accounts.google.com
#server:
#  port: 8081
#
#authorization-server:
#  issuer-url: http://10.48.17.124:8081
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2.server.authorization: TRACE
#
#clients:
#  issuer-server:
#    url: http://10.48.17.124:8080
#  redirect-url: http://10.48.17.124:8081/auth/callback
