plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example.did'
version = '3.0.0'
description = 'Verifier Example Server'

allprojects {
    repositories {
        mavenCentral()
        google()
        maven { url "https://repo.danubetech.com/repository/maven-public/" }
        maven { url "https://maven.scijava.org/content/repositories/public/" }
        maven { url "https://jitpack.io" }
    }

    configurations.all {
        resolutionStrategy {
            force 'org.bouncycastle:bcpkix-jdk18on:1.80'
            force 'org.bouncycastle:bcprov-jdk18on:1.80'
            force 'org.bouncycastle:bcutil-jdk18on:1.80'
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

jar {
    enabled = false
}

bootJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

ext {
    set('springCloudVersion', "2023.0.1")
}

springBoot {
    buildInfo()
}

dependencies {
    // SDK
    implementation project(':did-oid4vp-sdk-server')
    implementation project(':did-oid4vc-formatter-sdk-server')

    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-web-services'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    // Database (moved from SDK)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.liquibase:liquibase-core'
    runtimeOnly 'org.postgresql:postgresql'

    // API Documentation (moved from SDK)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Local SDK libraries
    implementation fileTree(dir: "libs", includes: ["*"])
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}