plugins {
	id 'java-library'
	id 'org.springframework.boot' version '3.2.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.omnione.did.oid4vc.oid4vci'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
    google()
    maven { url "https://repo.danubetech.com/repository/maven-public/" }
    maven { url "https://maven.scijava.org/content/repositories/public/" }
    maven { url "https://jitpack.io" }
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

bootJar {
	enabled = false
}

jar {
	enabled = true
    // Bundle local libs into the jar
    from {
        fileTree(dir: 'libs', include: ['*.jar']).collect { zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

ext {
	set('springCloudVersion', "2023.0.1")
}

dependencies {
    api project(':did-oid4vc-formatter-sdk-server')
    api fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-web-services'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'


    // Utilities
    api 'com.google.zxing:javase:3.5.1'

    compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}
