plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.github.DevOmniOneID'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.80'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.15.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.2'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.0'

    // Logging
    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'org.apache.logging.log4j:log4j-core:2.23.1'
    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.23.1'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    implementation fileTree(dir: "libs", includes: ["*"])
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            groupId = project.group
            artifactId = 'sd-jwt-sdk'
            version = project.version
        }
    }
}

jar {
    archiveBaseName = 'sd-jwt-sdk'
    enabled = true
    archiveClassifier = ''
}

// JavaDoc 비활성화
tasks.withType(Javadoc).configureEach {
    enabled = false
}

test {
    useJUnitPlatform()
}