# 로컬 개발 환경용 인가 서버 설정
issuer:
  server-ip: photospheric-nondyspeptically-donny.ngrok-free.dev
#  server-ip: 10.48.17.124
  server-port: 8082
  base-url: https://${issuer.server-ip}

# google login
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "YOUR-ACTUAL-CLIENT-ID"
            client-secret: "YOUR-ACTUAL-SECRET"
            scope:
              - openid
              - profile
              - email

oid4vc:
  auth:
    issuer-url: ${issuer.base-url}
    clients:
      client-id: "oid4vci-client"
      client-secret: "secret"
      redirect-url: ${issuer.base-url}/auth/callback
      redirect-uris:
        - https://oauth.pstmn.io/v1/callback
        - http://localhost:8081/auth/callback
      scopes:
        - openid
      android:
        client-id: "oid4vci-android"
        redirect-uris:
          - "org.omnione.did.sdk.oid4vc://callback"
        scopes:
          - "openid"
          - "eu.europa.ec.eudi.pid_vc_sd_jwt"
          - "eu.europa.ec.eudi.pid_mdoc"
          - "eu.europa.ec.eudi.mdl_mdoc"
      ios:
        client-id: "oid4vci-ios"
        redirect-uris:
          - "oid4vc-app://callback"
        scopes:
          - "openid"
          - "eu.europa.ec.eudi.pid_mdoc"
          - "eu.europa.ec.eudi.mdl_mdoc"
      issuer-server:
        url: ${issuer.base-url}